### ISSUE TITLE
Support of network-wide interface parameter

### ISSUE THREAD

**Issue by rbugajewski** [chef-brigade/dhcp-cookbook#36]
It looks like you can only set the interface attribute for the whole dhcpd server. It is not possible to assign a subnet to a specific NIC. I would expect to have an additional configuration parameter in the networks data bag, e.g.: `interface: "eth1"`.

**Comment by jmccann** [comment]
From what I understand if you declare a subnet the server will look for an interface on the same network to listen on.  So even if you globally set an interface if you declare subnets that it does not have an IP on it is just ignored.

```
[root@default-centos-64 dhcp]# dhcpd 
Internet Systems Consortium DHCP Server 4.1.1-P1
Copyright 2004-2010 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Not searching LDAP since ldap-server, ldap-port and ldap-base-dn were not specified in the config file
Wrote 0 leases to leases file.

No subnet declaration for eth0 (10.0.2.15).
** Ignoring requests on eth0.  If this is not what
   you want, please write a subnet declaration
   in your dhcpd.conf file for the network segment
   to which interface eth0 is attached. **


Not configured to listen on any interfaces!
```

I guess if your use case is that you have multiple interfaces on the same subnet you would want to specify which interface to actually use for that subnet.

Or maybe I'm missing something else as I'm not a DHCP expert. :wink:

**Comment by jmccann** [comment]
Closing for now.  Feel free to reopen and respond to my last statement if I'm wrong.
