### ISSUE TITLE
rename repo to dhcp-cookbook?

### ISSUE THREAD

**Issue by josephholsten** [chef-brigade/dhcp-cookbook#52]
while discussing how to simplify `source_url` & `issues_url`, I noticed we don't have common name pattens for cookbooks
https://github.com/chef-brigade/meta/pull/30#discussion_r35138902

any objection to renaming this to `dhcp-cookbook`?

**Comment by jmccann** [comment]
No objections from me

**Comment by PierreRambaud** [comment]
:+1:

**Comment by josephholsten** [comment]
dun
