### ISSUE TITLE
Attribute driven failover configuration?

### ISSUE THREAD

**Issue by jslusher** [chef-brigade/dhcp-cookbook#59]
I'm trying to gather this by reading the code, but I'm not having any success. So far I've set ['dhcp']['failover'] to true, and this:

    default['dhcp']['masters'] = [
      { :name => 'master1',
        :ipaddress => '10.100.0.27'
      }
    ]

I don't see that anything is getting configured in /etc/dhcp/dhcpd.conf

Is there an attribute-driven way to configure failover?

**Comment by spheromak** [comment]
you need to set `node['dhcp']['failover']` to true. 

Under the hood it will search for peers in the same domain. If you set `node['dhcp']['masters'] ` and `node['dhcp']['slaves']` it will not search, and instead use these maps to configure failover peers.

**Comment by jslusher** [comment]
So it seems like I set it up properly, but I don't know where to see if it's actually the case on the node itself. Is there some place in the dhcp configuration I can verify this has happened?

**Comment by jmccann** [comment]
So I haven't used the failover piece myself (yet) but it seems like you should see something in the dhcp.conf: https://github.com/chef-brigade/dhcp-cookbook/blob/7af940bab995fc7af75a9358047781f91b823322/templates/default/dhcpd.conf.erb#L36-L52

The path to that file varies depending on platform/version: https://github.com/chef-brigade/dhcp-cookbook/blob/master/attributes/default.rb#L61-L71

Snippets of the dhcp.conf being generated for you may be helpful.

**Comment by jslusher** [comment]
My problem was that I had `['dhcp']['master']` set to true, but no `['dhcp']['slaves']` set, so the @failover was false because of that, and therefore it was not adding the failover section. Thanks for pointing me in the right direction!

**Comment by jmccann** [comment]
Glad you figured it out.  If the docs were unclear of what was needed I would love for a PR to make them more clear for others in the future!  I'd do it myself but haven't used the feature yet myself so you are probably more familiar with it than me. :wink:
