### ISSUE TITLE
doc & practice a release

### ISSUE THREAD

**Issue by josephholsten** [chef-brigade/dhcp-cookbook#61]
I'd like to make sure we can still release this cookbook if we need to add a new maintainer. Could someone work to show me how to do a release?

**Comment by josephholsten** [comment]
I'm thinking of adding a standard release process doc to meta, it would be useful to know if you can release with this process: https://github.com/chef-brigade/nano-cookbook/blob/master/RELEASE.md

**Comment by jmccann** [comment]
Yea, I think that's legit.  That's pretty much the process I'm following currently, except I've been tagging with `#.#.#` vs `v#.#.#` and can easily adopt the latter.

Would you like me to add those notes to this cookbook's README.md or are we going to have them documented somewhere that I can link to?  I know it's already documented in that nano cookbook ... didn't know if you planned on adding an .md file to the meta repo with this outlined also.
