### ISSUE TITLE
support local-address for fixed address to listen

### ISSUE THREAD

**Issue by dyim42** [chef-brigade/dhcp-cookbook#66]
Add support for fixed address to have the dhcp server listen on. 

<code>
   # Add to /etc/dhcp/dhcpd.conf

   local-address 10.0.0.1;
</code>

**Comment by jmccann** [comment]
You should just be able to define `node['dhcp']['parameters']['local-address']` in either a wrapper cookbook, role or as a node attribute directly on the node.
